# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201004_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='startPopulation',
            field=models.IntegerField(choices=[(1, 'Random'), (2, 'Latin Hyper Cube')], default=1),
        ),
    ]
