# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20210105_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'Gaussian Process Bandits'), (2, 'Deep Deterministic Policy Gradients'), (3, 'Deep Neural Network'), (4, 'Multi Objective MPO')], default=1),
        ),
    ]
